matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: SWIFT_SNAPSHOT=5.2.3
    - os: osx
      osx_image: xcode11.4

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
